#comment-1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-deployment
  labels:
    app: second
spec:
  replicas: 5
  selector:
    matchLabels:
      app: second
  template:
    metadata:
      labels:
        app: second
    spec:
      containers:
      - name: second-container
        image: httpd:latest
        ports:
        - containerPort: 80
